//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF.MiClienteWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/IntroWCF")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiClienteWCF.IMiServicio")]
    public interface IMiServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Saludar", ReplyAction="http://tempuri.org/IMiServicio/SaludarResponse")]
        string Saludar(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Saludar", ReplyAction="http://tempuri.org/IMiServicio/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/DevuelveObjetoPersona", ReplyAction="http://tempuri.org/IMiServicio/DevuelveObjetoPersonaResponse")]
        ClienteWCF.MiClienteWCF.Persona DevuelveObjetoPersona(int id, string Nom, string Tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/DevuelveObjetoPersona", ReplyAction="http://tempuri.org/IMiServicio/DevuelveObjetoPersonaResponse")]
        System.Threading.Tasks.Task<ClienteWCF.MiClienteWCF.Persona> DevuelveObjetoPersonaAsync(int id, string Nom, string Tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/DevuelvePersona", ReplyAction="http://tempuri.org/IMiServicio/DevuelvePersonaResponse")]
        ClienteWCF.MiClienteWCF.Persona DevuelvePersona(int PersonaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/DevuelvePersona", ReplyAction="http://tempuri.org/IMiServicio/DevuelvePersonaResponse")]
        System.Threading.Tasks.Task<ClienteWCF.MiClienteWCF.Persona> DevuelvePersonaAsync(int PersonaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/DevuelveListaPersonas", ReplyAction="http://tempuri.org/IMiServicio/DevuelveListaPersonasResponse")]
        ClienteWCF.MiClienteWCF.Persona[] DevuelveListaPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/DevuelveListaPersonas", ReplyAction="http://tempuri.org/IMiServicio/DevuelveListaPersonasResponse")]
        System.Threading.Tasks.Task<ClienteWCF.MiClienteWCF.Persona[]> DevuelveListaPersonasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioChannel : ClienteWCF.MiClienteWCF.IMiServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioClient : System.ServiceModel.ClientBase<ClienteWCF.MiClienteWCF.IMiServicio>, ClienteWCF.MiClienteWCF.IMiServicio {
        
        public MiServicioClient() {
        }
        
        public MiServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Saludar(string Nombre) {
            return base.Channel.Saludar(Nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string Nombre) {
            return base.Channel.SaludarAsync(Nombre);
        }
        
        public ClienteWCF.MiClienteWCF.Persona DevuelveObjetoPersona(int id, string Nom, string Tel) {
            return base.Channel.DevuelveObjetoPersona(id, Nom, Tel);
        }
        
        public System.Threading.Tasks.Task<ClienteWCF.MiClienteWCF.Persona> DevuelveObjetoPersonaAsync(int id, string Nom, string Tel) {
            return base.Channel.DevuelveObjetoPersonaAsync(id, Nom, Tel);
        }
        
        public ClienteWCF.MiClienteWCF.Persona DevuelvePersona(int PersonaID) {
            return base.Channel.DevuelvePersona(PersonaID);
        }
        
        public System.Threading.Tasks.Task<ClienteWCF.MiClienteWCF.Persona> DevuelvePersonaAsync(int PersonaID) {
            return base.Channel.DevuelvePersonaAsync(PersonaID);
        }
        
        public ClienteWCF.MiClienteWCF.Persona[] DevuelveListaPersonas() {
            return base.Channel.DevuelveListaPersonas();
        }
        
        public System.Threading.Tasks.Task<ClienteWCF.MiClienteWCF.Persona[]> DevuelveListaPersonasAsync() {
            return base.Channel.DevuelveListaPersonasAsync();
        }
    }
}
